# Generated by Django 5.0.2 on 2024-03-18 16:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["title"], "verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="Suggested value automatically generated rom title. Must be unique.",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(help_text="Maximum 250 characters", max_length=250),
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("excerpt", models.TextField(blank=True)),
                ("body", models.TextField()),
                ("pub_date", models.DateTimeField(default=datetime.datetime.now)),
                ("slug", models.SlugField(unique_for_date="pub_date")),
                ("enable_comments", models.BooleanField(default=True)),
                ("featured", models.BooleanField(default=False)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Live"), (2, "Draft"), (3, "Hidden")], default=1
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("categories", models.ManyToManyField(to="weblog.category")),
            ],
            options={
                "verbose_name_plural": "Entries",
                "ordering": ["-pub_date"],
            },
        ),
    ]
