# Generated by Django 5.0.2 on 2024-03-20 15:13

import tagging.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblog", "0002_alter_category_options_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="body_html",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="entry",
            name="excerpt_html",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="entry",
            name="tags",
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="entry",
            name="excerpt",
            field=models.TextField(
                blank=True,
                help_text="A small portion of text to show as a preview on the main page. Can be blank",
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="title",
            field=models.CharField(help_text="Maximum 250 characters.", max_length=250),
        ),
    ]
